-- Global exercise and food libraries (from src/domain/data). Nutrition values are approximate, from USDA FoodData Central.

insert into public.exercises (id, name, muscle, region, equipment, instructions, alt_ids) values
  ('squat', 'Back squat', 'Quads', 'lower', 'Barbell', 'Bar on upper back, brace, sit down between the hips to depth you control, drive up through mid-foot.', array['hack','legpress','goblet']::text[]),
  ('rdl', 'Romanian deadlift', 'Hamstrings', 'lower', 'Barbell', 'Soft knees, push hips back keeping the bar close, stop when hamstrings limit range, stand tall.', array['dbrdl','legcurl']::text[]),
  ('legpress', 'Leg press', 'Quads', 'lower', 'Machine', 'Feet mid-platform, lower until hips start to tuck, press without locking knees hard.', array['hack','squat']::text[]),
  ('legcurl', 'Lying leg curl', 'Hamstrings', 'lower', 'Machine', 'Hips pinned, curl to full flexion, 2 s lowering.', array['seatcurl','rdl']::text[]),
  ('calf', 'Standing calf raise', 'Calves', 'lower', 'Machine', 'Full stretch at the bottom, pause, rise onto big toe.', '{}'),
  ('crunch', 'Cable crunch', 'Core', 'core', 'Cable', 'Kneel, rope by ears, flex the spine toward the floor, hips still.', array['kneeraise']::text[]),
  ('incdb', 'Incline DB press', 'Chest', 'upper', 'Dumbbell', 'Bench at 30°, shoulder blades set, lower to chest level, press slightly inward.', array['incbar','bench','fly']::text[]),
  ('csrow', 'Chest-supported row', 'Upper back', 'upper', 'Dumbbell', 'Chest on incline pad, row elbows toward hips, pause at the top.', array['dbrow','cablerow']::text[]),
  ('pulldown', 'Lat pulldown', 'Lats', 'upper', 'Cable', 'Slight lean back, drive elbows down to ribs, control the return to a full stretch.', array['ngpull','pullup']::text[]),
  ('dbsp', 'Seated DB shoulder press', 'Shoulders', 'upper', 'Dumbbell', 'Back supported, press up and slightly in, lower to ear height.', array['machsp']::text[]),
  ('lateral', 'Cable lateral raise', 'Shoulders', 'upper', 'Cable', 'Lead with the elbow, raise to shoulder height, slow lowering.', array['dblateral']::text[]),
  ('pushdown', 'Rope pushdown', 'Triceps', 'upper', 'Cable', 'Elbows fixed at sides, extend and split the rope at the bottom.', array['ohext']::text[]),
  ('hipthrust', 'Barbell hip thrust', 'Glutes', 'lower', 'Barbell', 'Upper back on bench, chin tucked, drive through heels to full hip extension, pause 1 s.', array['glutebridge','machthrust']::text[]),
  ('bss', 'Bulgarian split squat', 'Glutes', 'lower', 'Dumbbell', 'Rear foot on bench, torso slightly forward, lower under control. Weight is per dumbbell.', array['lunge','legpress']::text[]),
  ('hack', 'Hack squat', 'Quads', 'lower', 'Machine', 'Feet shoulder width, lower to depth, press through the whole foot.', array['legpress','squat']::text[]),
  ('seatcurl', 'Seated leg curl', 'Hamstrings', 'lower', 'Machine', 'Lean forward slightly for more stretch, curl fully, control up.', array['legcurl']::text[]),
  ('abduct', 'Hip abduction', 'Glutes', 'lower', 'Machine', 'Slight forward lean, push knees out, pause at the end.', '{}'),
  ('kneeraise', 'Hanging knee raise', 'Core', 'core', 'Bodyweight', 'Posterior pelvic tilt, raise knees to chest, no swing.', array['crunch']::text[]),
  ('bench', 'Bench press', 'Chest', 'upper', 'Barbell', 'Feet planted, slight arch, touch low chest, press back over shoulders.', array['incdb','machpress']::text[]),
  ('dbrow', 'One-arm DB row', 'Upper back', 'upper', 'Dumbbell', 'Hand and knee on bench, row toward hip, full stretch at the bottom.', array['csrow','cablerow']::text[]),
  ('ngpull', 'Neutral-grip pulldown', 'Lats', 'upper', 'Cable', 'Neutral handle, chest up, elbows to ribs.', array['pulldown']::text[]),
  ('fly', 'Machine chest fly', 'Chest', 'upper', 'Machine', 'Soft elbows, hug the arc, squeeze, slow return.', '{}'),
  ('facepull', 'Face pull', 'Rear delts', 'upper', 'Cable', 'Rope at face height, pull to forehead, rotate thumbs back.', '{}'),
  ('ezcurl', 'EZ-bar curl', 'Biceps', 'upper', 'Barbell', 'Elbows still, curl up, 2 s down.', array['dbcurl']::text[]),
  ('goblet', 'Goblet squat', 'Quads', 'lower', 'Dumbbell', 'Hold DB at chest, sit between hips, elbows inside knees.', array['squat']::text[]),
  ('dbrdl', 'DB Romanian deadlift', 'Hamstrings', 'lower', 'Dumbbell', 'As the barbell RDL, dumbbells along the thighs.', array['rdl']::text[]),
  ('incbar', 'Incline barbell press', 'Chest', 'upper', 'Barbell', '30° bench, bar to upper chest.', array['incdb']::text[]),
  ('machpress', 'Machine chest press', 'Chest', 'upper', 'Machine', 'Handles at mid-chest, press without shrugging.', array['bench']::text[]),
  ('cablerow', 'Seated cable row', 'Upper back', 'upper', 'Cable', 'Tall chest, row to lower ribs, stretch forward.', array['csrow']::text[]),
  ('pullup', 'Assisted pull-up', 'Lats', 'upper', 'Machine', 'Weight shown is assistance — lower is harder.', array['pulldown']::text[]),
  ('machsp', 'Machine shoulder press', 'Shoulders', 'upper', 'Machine', 'Seat so handles start at shoulder height.', array['dbsp']::text[]),
  ('dblateral', 'DB lateral raise', 'Shoulders', 'upper', 'Dumbbell', 'Slight lean forward, raise to shoulder height.', array['lateral']::text[]),
  ('ohext', 'Overhead cable extension', 'Triceps', 'upper', 'Cable', 'Face away, elbows forward, extend fully.', array['pushdown']::text[]),
  ('glutebridge', 'DB glute bridge', 'Glutes', 'lower', 'Dumbbell', 'Floor bridge with DB on hips.', array['hipthrust']::text[]),
  ('machthrust', 'Hip thrust machine', 'Glutes', 'lower', 'Machine', 'Pad across hips, drive to lockout.', array['hipthrust']::text[]),
  ('lunge', 'Walking lunge', 'Glutes', 'lower', 'Dumbbell', 'Long step, back knee toward floor. Weight per dumbbell.', array['bss']::text[]),
  ('dbcurl', 'Incline DB curl', 'Biceps', 'upper', 'Dumbbell', 'Arms hang behind torso, curl without swinging.', array['ezcurl']::text[]),
  ('deadlift', 'Conventional deadlift', 'Posterior chain', 'lower', 'Barbell', 'Bar over mid-foot, wedge in, push the floor away.', array['rdl']::text[]),
  ('legext', 'Leg extension', 'Quads', 'lower', 'Machine', 'Pause at the top, 3 s lowering.', '{}')
on conflict (id) do update set name = excluded.name, muscle = excluded.muscle, region = excluded.region, equipment = excluded.equipment, instructions = excluded.instructions, alt_ids = excluded.alt_ids;

insert into public.foods (id, user_id, name, basis, kcal, protein, carbs, fat, role, category, tags, source, estimated, serving, raw_id, cooked_id, yield, buy) values
  ('chicken_c', null, 'Chicken breast, skinless', 'cooked', 165, 31, 0, 3.6, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, 'chicken_r', null, 0.75, null),
  ('chicken_r', null, 'Chicken breast, skinless', 'raw', 120, 22.5, 0, 2.6, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, null, 'chicken_c', 0.75, '{"unit":"pack","g":500}'::jsonb),
  ('turkey', null, 'Turkey breast, sliced', 'prepared', 104, 17, 3.5, 2, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"pack","g":175}'::jsonb),
  ('beef_c', null, 'Lean ground beef 95%', 'cooked', 170, 26, 0, 7, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, 'beef_r', null, 0.72, null),
  ('beef_r', null, 'Lean ground beef 95%', 'raw', 137, 21.4, 0, 5, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, null, 'beef_c', 0.72, '{"unit":"pack","g":450}'::jsonb),
  ('salmon_r', null, 'Atlantic salmon', 'raw', 208, 20.4, 0, 13.4, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, null, 'salmon_c', 0.8, '{"unit":"fillet","g":150}'::jsonb),
  ('salmon_c', null, 'Atlantic salmon', 'cooked', 206, 22.1, 0, 12.4, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, 'salmon_r', null, 0.8, null),
  ('cod_c', null, 'Cod', 'cooked', 105, 22.8, 0, 0.9, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, 'cod_r', null, 0.78, null),
  ('cod_r', null, 'Cod', 'raw', 82, 17.8, 0, 0.7, 'protein', 'Meat & fish', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, null, null, 'cod_c', 0.78, '{"unit":"pack","g":400}'::jsonb),
  ('tuna', null, 'Tuna, canned in water', 'drained', 116, 25.5, 0, 0.8, 'protein', 'Pantry', array['Dairy-free','Gluten-free','High protein']::text[], 'USDA FoodData Central', false, '{"label":"can, drained","g":120}'::jsonb, null, null, null, '{"unit":"can","g":120}'::jsonb),
  ('tofu', null, 'Tofu, firm', 'raw', 144, 17.3, 2.8, 8.7, 'protein', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian','High protein']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"block","g":350}'::jsonb),
  ('eggs', null, 'Egg, whole', 'raw', 143, 12.6, 0.7, 9.5, 'protein', 'Dairy & eggs', array['Dairy-free','Gluten-free','Vegetarian']::text[], 'USDA FoodData Central', false, '{"label":"large egg","g":50}'::jsonb, null, null, null, '{"unit":"dozen","g":600}'::jsonb),
  ('eggw', null, 'Egg whites, liquid', 'raw', 48, 10, 0.7, 0.2, 'protein', 'Dairy & eggs', array['Dairy-free','Gluten-free','Vegetarian','High protein']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"carton","g":500}'::jsonb),
  ('yog', null, 'Greek yogurt, 0% plain', 'prepared', 59, 10.3, 3.6, 0.4, 'protein', 'Dairy & eggs', array['Gluten-free','Vegetarian','High protein']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"tub","g":750}'::jsonb),
  ('soyog', null, 'Soy yogurt, plain', 'prepared', 66, 5.5, 4, 3, 'protein', 'Dairy & eggs', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"tub","g":650}'::jsonb),
  ('cottage', null, 'Cottage cheese 2%', 'prepared', 84, 11, 4.3, 2.3, 'protein', 'Dairy & eggs', array['Gluten-free','Vegetarian','High protein']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"tub","g":500}'::jsonb),
  ('whey', null, 'Whey protein isolate', 'prepared', 380, 80, 8, 5, 'protein', 'Pantry', array['Gluten-free','Vegetarian','High protein']::text[], 'Custom · product label', false, '{"label":"scoop","g":30}'::jsonb, null, null, null, '{"unit":"tub","g":900}'::jsonb),
  ('rice_c', null, 'White rice, long-grain', 'cooked', 130, 2.7, 28.2, 0.3, 'carb', 'Grains & starches', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, 'rice_r', null, 3, null),
  ('rice_r', null, 'White rice, long-grain', 'raw', 365, 7.1, 80, 0.7, 'carb', 'Grains & starches', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, 'rice_c', 3, '{"unit":"bag","g":900}'::jsonb),
  ('quinoa_c', null, 'Quinoa', 'cooked', 120, 4.4, 21.3, 1.9, 'carb', 'Grains & starches', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, 'quinoa_r', null, 2.7, null),
  ('quinoa_r', null, 'Quinoa', 'raw', 368, 14.1, 64.2, 6.1, 'carb', 'Grains & starches', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, 'quinoa_c', 2.7, '{"unit":"bag","g":500}'::jsonb),
  ('pasta_c', null, 'Pasta, enriched', 'cooked', 158, 5.8, 30.9, 0.9, 'carb', 'Grains & starches', array['Dairy-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, 'pasta_r', null, 2.25, null),
  ('pasta_r', null, 'Pasta, enriched', 'raw', 371, 13, 74.7, 1.5, 'carb', 'Grains & starches', array['Dairy-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, 'pasta_c', 2.25, '{"unit":"box","g":450}'::jsonb),
  ('potato_r', null, 'Potato, white, flesh & skin', 'raw', 77, 2, 17.5, 0.1, 'carb', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, 'potato_c', 1, '{"unit":"bag","g":2270}'::jsonb),
  ('potato_c', null, 'Potato, boiled', 'cooked', 87, 1.9, 20.1, 0.1, 'carb', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, 'potato_r', null, 1, null),
  ('sweet_c', null, 'Sweet potato, baked', 'cooked', 90, 2, 20.7, 0.2, 'carb', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, 'sweet_r', null, 0.8, null),
  ('sweet_r', null, 'Sweet potato', 'raw', 86, 1.6, 20.1, 0.1, 'carb', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, 'sweet_c', 0.8, '{"unit":"each","g":200}'::jsonb),
  ('oats', null, 'Rolled oats', 'raw', 379, 13.2, 67.7, 6.5, 'carb', 'Grains & starches', array['Dairy-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"bag","g":1000}'::jsonb),
  ('bread', null, 'Whole-wheat bread', 'prepared', 247, 13, 41, 3.4, 'carb', 'Grains & starches', array['Dairy-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, '{"label":"slice","g":32}'::jsonb, null, null, null, '{"unit":"loaf","g":600}'::jsonb),
  ('tortilla', null, 'Flour tortilla, large', 'prepared', 306, 8.2, 50, 8, 'carb', 'Grains & starches', array['Dairy-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, '{"label":"wrap","g":62}'::jsonb, null, null, null, '{"unit":"pack of 8","g":496}'::jsonb),
  ('banana', null, 'Banana', 'edible', 89, 1.1, 22.8, 0.3, 'carb', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, '{"label":"medium, peeled","g":118}'::jsonb, null, null, null, '{"unit":"each","g":118}'::jsonb),
  ('blueb', null, 'Blueberries', 'raw', 57, 0.7, 14.5, 0.3, 'carb', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"pint","g":310}'::jsonb),
  ('lentils', null, 'Lentils, boiled', 'cooked', 116, 9, 20.1, 0.4, 'carb', 'Pantry', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, 'lentil_r', null, 2.4, null),
  ('lentil_r', null, 'Lentils, dry', 'raw', 352, 24.6, 63.4, 1.1, 'carb', 'Pantry', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, 'lentils', 2.4, '{"unit":"bag","g":900}'::jsonb),
  ('chick', null, 'Chickpeas, canned', 'drained', 139, 7, 22.5, 2.1, 'carb', 'Pantry', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"can, drained","g":250}'::jsonb),
  ('avocado', null, 'Avocado', 'edible', 160, 2, 8.5, 14.7, 'fat', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, '{"label":"medium, edible","g":136}'::jsonb, null, null, null, '{"unit":"each","g":136}'::jsonb),
  ('oil', null, 'Olive oil', 'prepared', 884, 0, 0, 100, 'fat', 'Pantry', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, '{"label":"tbsp","g":13.5}'::jsonb, null, null, null, '{"unit":"bottle","g":500}'::jsonb),
  ('almonds', null, 'Almonds', 'raw', 579, 21.2, 21.6, 49.9, 'fat', 'Pantry', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"bag","g":400}'::jsonb),
  ('pb', null, 'Peanut butter, smooth', 'prepared', 588, 25, 20, 50, 'fat', 'Pantry', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, '{"label":"tbsp","g":16}'::jsonb, null, null, null, '{"unit":"jar","g":500}'::jsonb),
  ('cheddar', null, 'Cheddar cheese', 'prepared', 403, 24.9, 1.3, 33.1, 'fat', 'Dairy & eggs', array['Gluten-free','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"block","g":400}'::jsonb),
  ('feta', null, 'Feta cheese', 'prepared', 264, 14.2, 4.1, 21.3, 'fat', 'Dairy & eggs', array['Gluten-free','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"pack","g":200}'::jsonb),
  ('hummus', null, 'Hummus', 'prepared', 166, 7.9, 14.3, 9.6, 'fat', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"tub","g":283}'::jsonb),
  ('broccoli_c', null, 'Broccoli, steamed', 'cooked', 35, 2.4, 7.2, 0.4, 'veg', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, 'broccoli_r', null, 0.95, null),
  ('broccoli_r', null, 'Broccoli', 'raw', 34, 2.8, 6.6, 0.4, 'veg', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, 'broccoli_c', 0.95, '{"unit":"head","g":500}'::jsonb),
  ('spinach', null, 'Spinach', 'raw', 23, 2.9, 3.6, 0.4, 'veg', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"bag","g":300}'::jsonb),
  ('greens', null, 'Mixed salad greens', 'raw', 20, 1.5, 3.5, 0.2, 'veg', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"box","g":142}'::jsonb),
  ('peppers', null, 'Bell pepper', 'raw', 26, 1, 6, 0.3, 'veg', 'Produce', array['Dairy-free','Gluten-free','Vegan','Vegetarian']::text[], 'USDA FoodData Central', false, null, null, null, null, '{"unit":"each","g":150}'::jsonb)
on conflict (id) do update set name = excluded.name, basis = excluded.basis, kcal = excluded.kcal, protein = excluded.protein, carbs = excluded.carbs, fat = excluded.fat, role = excluded.role, category = excluded.category, tags = excluded.tags, source = excluded.source, serving = excluded.serving, raw_id = excluded.raw_id, cooked_id = excluded.cooked_id, yield = excluded.yield, buy = excluded.buy;
